### PR TITLE
Enable Users to be filtered by whether they are a Partner admin

### PR DESCRIPTION
**Pull request by SangilYun**
### Issue link / number:
https://github.com/chaynHQ/bloom-backend/issues/443#issue-2331941856
### What changes did you make?
added logic to handle `IS NOT NULL`

### Why did you make the changes?
to be able to filter users by whether they are a partner admin or not.

<!--- PR CHECKLIST: PLEASE REMOVE BEFORE SUBMITTING —>
Before submitting, check that you have completed the following tasks:
- [ ] Answered the questions above.
- [ ] Read Chayn's Contributing Guidelines in the CONTRIBUTING.md file.
- [ ] Enabled "Allow edits and access to secrets by maintainers" on this PR.
- [ ] If applicable, include images in the description.
After submitting, please be available for discussion. Thank you!

### CODE REVIEW

**Comment by kyleecodes** [comment]
@SangilYun Just to verify, were you able to test that this worked?
Thank you!

**Comment by SangilYun** [comment]
> @SangilYun Just to verify, were you able to test that this worked? Thank you!

@kyleecodes I tested it by sending HTTP requests to the server from the client side with and without URI encoded object that looks like this and I was able to get only partner admin accounts.

```
 {
    "email": "test@test.com",
    "partnerAdmin": {"partnerAdminId": "IS NOT NULL"},
}
```

Did you get a different result when you tested it? If you have any specific scenarios you'd like me to test, please let me know.
Thank you!

**Review by kyleecodes — APPROVED** [review]
LGTM!

**Comment by eleanorreem** [comment]
Merged ! Thanks!

**Pull request merged**
