### PR TITLE
Remove unnecessary joins from develop branch

### PR DESCRIPTION
**Pull request by reidn3r**
Now, from develop branch:
- These change tries to solve the issue #454 
- Refactored the getUserByFirebaseId function to only fetch the user data, removing unnecessary joins/relations.
- Searched for any functions that rely on req['userEntity'] to ensure no existing functionality is broken. I found no instances of such functions, so it seems ok.
- Ran all tests and confirmed they passed successfully

### CODE REVIEW

**Comment by eleanorreem** [comment]
@reidn3r Thanks for this! This all works for me - the git history is just a bit strange. Is there any way of you fixing this?

**Comment by reidn3r** [comment]
@eleanorreem Maybe it was strange because my branch was some commits behind from base branch?? I've updated the branch via GitHub, and I believe it's correct now.

Sorry for these mistakes, its my first open source contribution 😬

**Comment by kyleecodes** [comment]
@reidn3r Thanks for opening a new PR. 
I see the same issue persist. I suggest syncing your forked develop branch, creating a new branch from the updated develop branch, and reimplementing the same changes in a new PR. See guidance on how to update your fork here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by reidn3r** [comment]
@kyleecodes @eleanorreem 
I created a new branch from the synced develop branch and reimplemented the code. I opened a new PR and you can find it [here](https://github.com/chaynHQ/bloom-backend/pull/646)

Hope it's correct now

**Pull request closed without merging**
