### PR TITLE
Srodif/create deleted at column

### PR DESCRIPTION
**Pull request by srodif**
### Issue link / number:
https://github.com/chaynHQ/bloom-backend/issues/530

### What changes did you make?
Added deletedAt column at user table and the database migration.

### Why did you make the changes?
Preference of the team for the deletion date data to have a separate column.

### Did you run tests?
Yes

Please give any feedback to make this PR more complete, thank you in advance for your time!
Requested as reviewers in issue:
@eleanorreem 
@annarhughes

### CODE REVIEW

**Review by kyleecodes — CHANGES_REQUESTED** [review]
Hi @srodif, thanks for this PR and patience as our devs were out of office. 
This looks almost good to merge, just needs tweaked to pass tests.
In addition to updating the mockData as you did, the userEntity object in `src/partner-admin/partner-admin-auth.guard.spec.ts` also needs updated with deleteAt in order to pass tests.

Were you able to run tests locally?

**Comment by srodif** [comment]
Hello @kyleecodes ! 
Thank for your time and your review on this! I updated the userEntity object in `src/partner-admin/partner-admin-auth.guard.spec.ts` too. I also was able to run the tests locally. 
If you notice anything else that needs to change or that is missing, please let me know.

**Review by kyleecodes — CHANGES_REQUESTED** [review]
Hi @srodif, thanks for your patience as I was out of office.!

1. This migration is close, but incomplete. It needs to set the user.deletedAt column to the date of user.updatedAt where the user.active is set to false (see action item 2 in issue).

2. I don't see application code added here that updates deletedAt when a user is deleted. Is there something I'm missing, or does it need to be implemented?

Thanks!

**Comment by srodif** [comment]
Hello @kyleecodes !

You are right, I missed the second action item. I may have been confused with the title and scope of issue #531. So, for your first point I will add the code. For the second point, I also want to make the addition, I am just not sure if this is taking over #531 too.

Thank you for your time and response!

**Comment by eleanorreem** [comment]
@srodif Thanks for your great work so far!

The migration doesn't cover the work needed for #531. The migration is a data cleanup of previous entries.  #531 covers changing the service method going forward. Hope that makes sense.

**Comment by eleanorreem** [comment]
@srodif I have merged and will add the follow up migration in another ticket! Thanks

**Pull request merged**
