### PR TITLE
Introduce ALREADY_APPLIED error code for duplicate partner access code usage

### PR DESCRIPTION
**Pull request by mayank-sahai**
### Issue link / number:
https://github.com/chaynHQ/bloom-backend/issues/387

### What changes did you make?
This commit introduces a new error code, ALREADY_APPLIED (along with the related test cases). This error will be returned when the access code has already been applied to the account.
Also handled the case when the access code is already used by another user. In this scenario, an ALREADY_IN_USE error will be returned.

### Why did you make the changes?
To provide a more accurate error message for users who attempt to apply a partner access code that has already been used with their account or another user's account.

<!--- PR CHECKLIST: PLEASE REMOVE BEFORE SUBMITTING —>
Before submitting, check that you have completed the following tasks:
- [ ] Answered the questions above.
- [ ] Read Chayn's Contributing Guidelines in the CONTRIBUTING.md file.
- [ ] Enabled "Allow edits and access to secrets by maintainers" on this PR.
- [ ] If applicable, include images in the description.
After submitting, please be available for discussion. Thank you!

### CODE REVIEW

**Comment by kyleecodes** [comment]
Thank you @mayank-sahai 
The dev team is off until Monday and will review then.👏

**Review by eleanorreem — APPROVED** [review]
Thanks so much for this contribution @mayank-sahai ⭐ All looks great to me 😄

**Comment by mayank-sahai** [comment]
@eleanorreem can you also review my frontend MR and let me know if any change is required? thanks🙌

**Comment by eleanorreem** [comment]
Absolutely ! Sorry i didn't see that PR either. We've set up better notifications now 🤦 I will do that today as well ⭐  Thats fab!

**Pull request merged**
